version: '2'
services:
  telebot:
    container_name: epaper--bot-telegram
    build: .
    environment:
      - TELEGRAM_BOT_TOKEN=
    volumes:
      - 'telegramDatabase:/usr/src/app/databases'

volumes:
  telegramDatabase:
    driver: local